# Generated by Django 3.2.15 on 2022-09-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20220925_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_url',
            field=models.CharField(default='', max_length=254),
        ),
    ]
