# Generated by Django 3.2.15 on 2022-09-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_order_receipt_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt_url',
        ),
    ]
