# Generated by Django 3.2.15 on 2022-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_remove_order_receipt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='UK', max_length=40),
        ),
    ]
