# Generated by Django 3.2.15 on 2022-09-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_imdb_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imdb_rating',
            new_name='imdbrating',
        ),
    ]
