# Generated by Django 3.2.15 on 2022-10-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_grade_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
